---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tasmobackup
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      type: statefulset
    image:
      repository: docker.io/danmed/tasmobackupv1
      tag: 1.05
    env:
      TZ: "${TIMEZONE}"
      DBTYPE: "sqlite"
      DBNAME: "data/tasmobackup"
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/icon: mdi:backup-restore
        hosts:
          - host: &host "tasmobackup.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: tasmobackup-tls
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
    volumeClaimTemplates:
      - name: data
        mountPath: /var/www/html/data
        accessMode: ReadWriteOnce
        size: 200Mi
        storageClass: ceph-block
        labels:
          snapshot.home.arpa/enabled: "true"
    persistence:
      backups:
        enabled: true
        type: nfs
        server: ${HOME_NAS_IP}
        path: volume1/Kubernetes/Tasmobackup
        mountPath: /var/www/html/data/backups
        readOnly: true
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 500Mi
