apiVersion: v1
kind: Secret
metadata:
    name: msfarmer-secrets-001
    namespace: default
stringData:
    MSAccount_0_USERNAME: ENC[AES256_GCM,data:NjCmpht8rmq1MBg/DG2VvKUOPAHoBz8cG+Y=,iv:DtHYwDNzDu8ZIldbD51Tret07Z9Sg3+mErrH9ImO51Y=,tag:bLms8d9hI8+jlzID8KyVpg==,type:str]
    MSAccount_0_PASSWORD: ENC[AES256_GCM,data:iTVFhH7rJqxdNBWIbsFtsQ==,iv:NZApg7Tl/w+AWaCer4CWyjxOLFU2ivUKHD2pRfdpUgw=,tag:3qVGiCtKBrZtX4bJj7lEAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbFUrTnZBRG9XUmViTlNL
            eWEyaVR0TmlYOEJ4YjFiVmh1WUpZTS9wS2hVCmd3dlJJWW5JRmRidjRjaWNFVVg4
            V0FlbEFYUzRDVjQzUVlBYm5DQVNTdVEKLS0tIG5JclZvTUFGUGZxbVJoNE5odXBW
            bzYvb0NZVFRtbDRBUHBLSFlDaFVsYmcKSp+oZYnIsYjVDzginizAooHwKzZ6nQT/
            96MeTzUYfU8vCcU/nzYahGswHctQTXrNFmyL2+lu6evEXAsCWwnDRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T19:06:28Z"
    mac: ENC[AES256_GCM,data:Awiq2FfaIuLlFWw/ghlqas6ZdW9XZgIQ9e1ltE/zOVPQSQF1aVHwGc7IElDxBk3anvAcCkHI30povUIqiVpY5oPPV6HjU8ow3O0ReIffvX2q93C+eA0HsQawc2dOOvU4VgRr02T3DdCYn3aU1eEJYJEf6xd3p6fR3D6ALZXIswI=,iv:eC6nL/11F5Ea42tzQUUPYt1egWIrskDY4yPluu5ZhRc=,tag:eZ8JGy8tt14uMzB9CJLDfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: msfarmer-secrets-002
    namespace: default
stringData:
    MSAccount_0_USERNAME: ENC[AES256_GCM,data:siAHY1QQDizrvLhg0eliBuQosJOkNg==,iv:Rxs5Ez5qk3ZJhpyi/VSNi+zh8Wnif5Qz7O67dJd4fh0=,tag:DURejuC9CNN6DWHkCop98Q==,type:str]
    MSAccount_0_PASSWORD: ENC[AES256_GCM,data:ioMblmYvZ1mKWsg=,iv:QbU0mbQ26dUvJcvTzM6HueqLcggTKzYSb1zKWUfLPuk=,tag:WvTagPJw583KHZRn6xX+OQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbFUrTnZBRG9XUmViTlNL
            eWEyaVR0TmlYOEJ4YjFiVmh1WUpZTS9wS2hVCmd3dlJJWW5JRmRidjRjaWNFVVg4
            V0FlbEFYUzRDVjQzUVlBYm5DQVNTdVEKLS0tIG5JclZvTUFGUGZxbVJoNE5odXBW
            bzYvb0NZVFRtbDRBUHBLSFlDaFVsYmcKSp+oZYnIsYjVDzginizAooHwKzZ6nQT/
            96MeTzUYfU8vCcU/nzYahGswHctQTXrNFmyL2+lu6evEXAsCWwnDRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T19:06:28Z"
    mac: ENC[AES256_GCM,data:Awiq2FfaIuLlFWw/ghlqas6ZdW9XZgIQ9e1ltE/zOVPQSQF1aVHwGc7IElDxBk3anvAcCkHI30povUIqiVpY5oPPV6HjU8ow3O0ReIffvX2q93C+eA0HsQawc2dOOvU4VgRr02T3DdCYn3aU1eEJYJEf6xd3p6fR3D6ALZXIswI=,iv:eC6nL/11F5Ea42tzQUUPYt1egWIrskDY4yPluu5ZhRc=,tag:eZ8JGy8tt14uMzB9CJLDfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: msfarmer-secrets-003
    namespace: default
stringData:
    MSAccount_0_USERNAME: ENC[AES256_GCM,data:/d1ddtmgWuJQIDFQw3BAB8TaXTJw6Q==,iv:lhswBZimNglQK5odcoCH2hIhYwjq5FI8mhTRx2l2Qw0=,tag:mhLq0I29rNzIKtsSFT4vwA==,type:str]
    MSAccount_0_PASSWORD: ENC[AES256_GCM,data:svASfR+r9XWU4YPDngx1,iv:Aj1e+3TeOS0duEcJtWt5KsBiIpDZ7nAj+u43+9hgb1E=,tag:eUtb0n+drpfAFAeUFvlg2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbFUrTnZBRG9XUmViTlNL
            eWEyaVR0TmlYOEJ4YjFiVmh1WUpZTS9wS2hVCmd3dlJJWW5JRmRidjRjaWNFVVg4
            V0FlbEFYUzRDVjQzUVlBYm5DQVNTdVEKLS0tIG5JclZvTUFGUGZxbVJoNE5odXBW
            bzYvb0NZVFRtbDRBUHBLSFlDaFVsYmcKSp+oZYnIsYjVDzginizAooHwKzZ6nQT/
            96MeTzUYfU8vCcU/nzYahGswHctQTXrNFmyL2+lu6evEXAsCWwnDRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T19:06:28Z"
    mac: ENC[AES256_GCM,data:Awiq2FfaIuLlFWw/ghlqas6ZdW9XZgIQ9e1ltE/zOVPQSQF1aVHwGc7IElDxBk3anvAcCkHI30povUIqiVpY5oPPV6HjU8ow3O0ReIffvX2q93C+eA0HsQawc2dOOvU4VgRr02T3DdCYn3aU1eEJYJEf6xd3p6fR3D6ALZXIswI=,iv:eC6nL/11F5Ea42tzQUUPYt1egWIrskDY4yPluu5ZhRc=,tag:eZ8JGy8tt14uMzB9CJLDfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: msfarmer-secrets-004
    namespace: default
stringData:
    MSAccount_0_USERNAME: ENC[AES256_GCM,data:RGlHpqJXQJ1l+G5mbOKN4Eq9kic=,iv:taGVnAobMjCRFaGPxUWHHfEtHsxxO/eogsk4kQAEL0c=,tag:MTs60af2e+4CHZOUBxHgyw==,type:str]
    MSAccount_0_PASSWORD: ENC[AES256_GCM,data:mdwIl8AttspX6zLD,iv:z1LqNOqhM7OP+3giVapMHMq+AzvYyVHW+etpdkGHD5s=,tag:W3sQh6qMXUiFK6U5JgBDxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbFUrTnZBRG9XUmViTlNL
            eWEyaVR0TmlYOEJ4YjFiVmh1WUpZTS9wS2hVCmd3dlJJWW5JRmRidjRjaWNFVVg4
            V0FlbEFYUzRDVjQzUVlBYm5DQVNTdVEKLS0tIG5JclZvTUFGUGZxbVJoNE5odXBW
            bzYvb0NZVFRtbDRBUHBLSFlDaFVsYmcKSp+oZYnIsYjVDzginizAooHwKzZ6nQT/
            96MeTzUYfU8vCcU/nzYahGswHctQTXrNFmyL2+lu6evEXAsCWwnDRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T19:06:28Z"
    mac: ENC[AES256_GCM,data:Awiq2FfaIuLlFWw/ghlqas6ZdW9XZgIQ9e1ltE/zOVPQSQF1aVHwGc7IElDxBk3anvAcCkHI30povUIqiVpY5oPPV6HjU8ow3O0ReIffvX2q93C+eA0HsQawc2dOOvU4VgRr02T3DdCYn3aU1eEJYJEf6xd3p6fR3D6ALZXIswI=,iv:eC6nL/11F5Ea42tzQUUPYt1egWIrskDY4yPluu5ZhRc=,tag:eZ8JGy8tt14uMzB9CJLDfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: msfarmer-secrets-005
    namespace: default
stringData:
    MSAccount_0_USERNAME: ENC[AES256_GCM,data:A1XGZfQVqwVxg0LJRwm/g9uhs1g=,iv:BjLV6F4sOSXp7p72xM1ksR3XDwssZCRjO8EvotToP0w=,tag:kUQ0KXpPAhB8rxqD7duH6A==,type:str]
    MSAccount_0_PASSWORD: ENC[AES256_GCM,data:p2cUdIBQbfAvNw==,iv:VgJv9eg5pTvUvqdlwfeA0u+TUzYPtnisH3ld1SknYI4=,tag:OAvh12q9GiX+CPJizzDTcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbFUrTnZBRG9XUmViTlNL
            eWEyaVR0TmlYOEJ4YjFiVmh1WUpZTS9wS2hVCmd3dlJJWW5JRmRidjRjaWNFVVg4
            V0FlbEFYUzRDVjQzUVlBYm5DQVNTdVEKLS0tIG5JclZvTUFGUGZxbVJoNE5odXBW
            bzYvb0NZVFRtbDRBUHBLSFlDaFVsYmcKSp+oZYnIsYjVDzginizAooHwKzZ6nQT/
            96MeTzUYfU8vCcU/nzYahGswHctQTXrNFmyL2+lu6evEXAsCWwnDRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T19:06:28Z"
    mac: ENC[AES256_GCM,data:Awiq2FfaIuLlFWw/ghlqas6ZdW9XZgIQ9e1ltE/zOVPQSQF1aVHwGc7IElDxBk3anvAcCkHI30povUIqiVpY5oPPV6HjU8ow3O0ReIffvX2q93C+eA0HsQawc2dOOvU4VgRr02T3DdCYn3aU1eEJYJEf6xd3p6fR3D6ALZXIswI=,iv:eC6nL/11F5Ea42tzQUUPYt1egWIrskDY4yPluu5ZhRc=,tag:eZ8JGy8tt14uMzB9CJLDfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
