kind: ENC[AES256_GCM,data:GrFV1E0f,iv:Hof4ptuPKYqCzIer0xlGTWa/gLkloRLSPVt6G5WrfiA=,tag:EoJwXSDWLw9sXqJMFdqqFA==,type:str]
ansible_user: ENC[AES256_GCM,data:MK/ZRVgK,iv:8v6WklhQuOVE3qTwtOM+PstrO6G2JhiWUHyXQs8LXuo=,tag:TCRr02AbUbLnFdUZ8Rj3fQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:cF7y3q+DyKq7tzqC5HIn,iv:NyysCsCrI2r/vityOD2J/V3bVVWC7PHyDI7/krVN7i4=,tag:O8b0pjT38pOguUeb10y+Uw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRHdwUnlGa2djZFFneEhU
            enRtWGhYMHgweTRBNERTZ3gvYzJlcFZJcXcwCkxkRDE0d2dZd2tIa2d6UEIyejEv
            bWRaakNpN09vVmd6V3VqcTNjYm1DdVUKLS0tIHhZaGFMTFhRUVFtUXp1STA4WUQ5
            bVl5SFRxRE00NUZBdENYMnhRZ3p4QjgKRD2Ny5EbaGv8xaUPAeE7V7yqudcNEPjX
            ciXC8/X/F786tTB0D4vk1VnsBYmJx1aVtIaRwWXkhqQ344R/WP5dUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-29T16:40:27Z"
    mac: ENC[AES256_GCM,data:HumyGKa2oQt4GV3ZbTuTjCaZDa2DzQwpkkrem4qgyGp5WIOwlYM73SqZVHK4r5vtji/Ca+XJ9xEolEpCXqMI7FJGL/xF/qUEOj8etDH83sWZgGzRVUWS4cveLdsEERRo3D8T8cRoWr9g50Rhtb04lZ3T8Au5l0l419hqMiG8fio=,iv:d97Ehcw6Yb7+NloCk22tnykVS41BdaDtKylFZ4/YdKM=,tag:BAQnv+8CD0qvUZufOTt+ZQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
