kind: ENC[AES256_GCM,data:dtNYWnyS,iv:4qk+2yBi7w4U20iGrZarYTPOZ2eFUyiRtoLaR571r8w=,tag:rsVO0RpWcZzrdqjRklsctg==,type:str]
ansible_user: ENC[AES256_GCM,data:i4eMIaV0,iv:JBOr/92HuUlqp1Mhl0Sk/mFSB1+TxZZTnVkophOq2c8=,tag:wSuVMavCrIEmVvFmeh19nQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:8Bum1B1JRnd2rtKAV59l,iv:Z6MxYYbVxUN9CsrGyn3XqfkAIwzxyS763pYM51cwK/E=,tag:iaPDn7/xySb5eq/h3ZkVcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbUpDbDU5MzVERXA1YzBj
            eWFSbzB4UTNFQnZuSDZCU1dsRDZrYzg3ZkNvCm5uOG94bFhFdTIybk9RbHA0M2lV
            ZDM4ZjE3NklVdGtEcEh0TVVrcG43cmcKLS0tIGUxWVZjeGdXRUk5Z0F5UnVraFRK
            Z3UrRGdMblJYMDRXYnlmR2FXNkJjdjQKG/KgIJFrz7LBP1tGySRLKOZFueKVdw3Z
            sNjNfb/dAtTaUN0E9Nhds2AhaVa2WKlsOwwJsDOMwz1xXMVVw37XhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-29T16:40:27Z"
    mac: ENC[AES256_GCM,data:ZtiQ9Vo35W3W45n+bQpQWZBO/qomliuNGZZ8PcVMfOncv+vem9zinaEPi49Asyb59XCMcF+LFZpc/ba1MsAa+blQai4VmEIp1l9aWGcfa9+lncnKhZuN4cB33bXNnNTalopXffdGjP/Lr5bWMd6qSaP9l/Son+W9CmlB1tSO/OU=,iv:vqAHacYJvowwAVM3wpIvV5jdSNpLJHtuE041IhzJz04=,tag:zPQ6a3nyQF1IUOw/odLllQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
