apiVersion: v1
kind: Secret
metadata:
    name: emqx-secret
    namespace: flux-system
stringData:
    admin_password: ENC[AES256_GCM,data:Qdui1BtYR4WdI4ErH28=,iv:dnlSfPtTJccjXCaQVu43yFUxbv3802nau7MkseUB0M8=,tag:HzQnz3b1n/Uf1dLiiGVPSA==,type:str]
    user_1_username: ENC[AES256_GCM,data:/FPXy51WB2t3KxWmXw==,iv:fG2BRPHiTtuigBh76Q/dSSm9QCxC9VxcKqqugPkY6Xw=,tag:gW64jr7oZrOMc2jz8GQ2+w==,type:str]
    user_1_password: ENC[AES256_GCM,data:3tIoMemn++lsO0cM,iv:HrX3lAwuTpLFW0qQwRiy6P3je5mpqjLrh6JXbBp02WE=,tag:FOYhN6zd7p8XmEa03hZp8g==,type:str]
    user_2_username: ENC[AES256_GCM,data:ZfEqrpNBHeMI,iv:B56Xn/f4J9dyvYq7Mb0HR4/V8n1WuhCaRMsMLIxqS0Y=,tag:LZV9XhFHwLjjdbArkB7wtQ==,type:str]
    user_2_password: ENC[AES256_GCM,data:GRKf0TTbG0ppkBQr,iv:FaQ9aq0BO8ijxJOV0sRgELInYpeQuNwDcSVDU6jhsDs=,tag:Gxlgv3PGWCsKCbQI3wezNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbk94SkJUdzF5Unk5dXRw
            UUJ0eU1TTm1OWTJsVUJmTFFjR3N5Vm10dVQwClpKN0NQbTlwdEl3SUdjSHExYzY2
            V0E2QjNFb01MN2o4Q1pjYTRHTU9KS2MKLS0tIGRpek5hdDEzaUNySnZxcktPMXRF
            ZlpRVmhZTmNCMUZxekx3dFp5eCs2bDgKLOKAwcQxJI3esUFsXR1ws86gRGW0dg8P
            LATjwpCFhA7tN2MIDEqJGS7uxuq4zdUmjleB7NNtNOE0cOLkB8K4sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-15T22:02:52Z"
    mac: ENC[AES256_GCM,data:ZErilcPTmuHUcNFAj/8Zo7x4/wxcy0S2NpRK+X9Jc1SZMESyVtNQjTt1HCHro4w0aZBnH68dfxTjKtzw8INg1qnDako3uepeYMcMN4/5Avrdwo/ZYyS28UFKX/CLNul9+KRqVeTBk8viHrdawNBFnHl5TXuaMUX6n4Bdb9zSyIA=,iv:qDaEb53wzkjZYtqK1NXM+pfGLerFW995v9kc73OMrYM=,tag:x8nNPIFBBWskqmAr6ywbRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
