apiVersion: v1
kind: Secret
metadata:
    name: emqx-secret
    namespace: default
stringData:
    admin_password: ENC[AES256_GCM,data:t/HsaO7DaoRZlyAs1Mc=,iv:xccH8cIdk4uEExqTkXkSCG2m4ObAXpWjx+bPyiNsreI=,tag:/2ieJM63dl9SOBvK+Dhg+w==,type:str]
    user_1_username: ENC[AES256_GCM,data:7ckux6nOa3KsPQ==,iv:H/trwMJfAKwdi+oU6m5xOwflh6E2qa4afvdLXQR5zBw=,tag:oR/rvbkSFxc2jz43d4YCwg==,type:str]
    user_1_password: ENC[AES256_GCM,data:lBfT6LFRxxeD+llcVWs=,iv:X8fNOub8XhYzNfRB+Wbg8xVtsbvxdavSwTd0wXM749Y=,tag:yGtjmTbEyyNVfLboHHT+jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MzJQUHdYL1B3WGZZVXFS
            WWNBZldHaTFQUFFNb1IwQm00Rm51OTBHRlJzCjVkQVk3T0xBbWVBU1FoRGtDbG9Z
            aUZOYlhLOTgyTitLOXFiN2xSWHF4TU0KLS0tIFNaV21NbGM0aFJ6cUsrbERjWkg0
            K1kwL2k1aXFkYnpLV2NwRjYrbVdZUk0KK9mcUFnUirUmTWuX9etPggaEN50uw+gw
            mJD74jx6zoDa9Dac2KfhshfKRaT2D6DVuZRabZvUFXXGvC+WRP7yIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-15T19:51:51Z"
    mac: ENC[AES256_GCM,data:TU5amK74NBbc5hoo0N7DN/eEs3FiLk6/Gxeu/qY/bLRzv/aqkOnqv9VNw6LItb3/OX0W3lOU8ogWEwpHE2gpM/L/cL/2DA/mZXlzo7tnE9yHjHKtoQNkXoh/LT9fiJu7bAlfv54NjcHhhIUIuqkBj0FQApSsrPGX9tCHK1WIOoI=,iv:MRyNUgiJVN6kA6j4h7E+8lT6ujV0/8J/ytWLshCatFY=,tag:EB3KUA1NePQZOYw2FOtS6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
