apiVersion: v1
kind: Secret
metadata:
    name: emqx-secret
    namespace: flux-system
stringData:
    admin_password: ENC[AES256_GCM,data:Qdui1BtYR4WdI4ErH28=,iv:dnlSfPtTJccjXCaQVu43yFUxbv3802nau7MkseUB0M8=,tag:HzQnz3b1n/Uf1dLiiGVPSA==,type:str]
    user_1_username: ENC[AES256_GCM,data:AWUjnUQewAggF/d10g==,iv:SiLuaVKYnscX00cS6ETJKNCeEc5oAhjBXnR84iNSuLU=,tag:S1B/dV0cj0fKqRMuFXimBg==,type:str]
    user_1_password: ENC[AES256_GCM,data:3tIoMemn++lsO0cM,iv:HrX3lAwuTpLFW0qQwRiy6P3je5mpqjLrh6JXbBp02WE=,tag:FOYhN6zd7p8XmEa03hZp8g==,type:str]
    user_2_username: ENC[AES256_GCM,data:ZyQKSU0SE4wq,iv:Cr9iMESdZhJltWJ3awaj9TIA4/pI9CY5E5CcGSFGBSg=,tag:mmEGhNESt1KPjD8wgiHNrg==,type:str]
    user_2_password: ENC[AES256_GCM,data:4rw2BjLFIDd+8A+8,iv:FGteZtJp4uuZoc9RaBrbtuyyMRteCH4Yy1W+pKhAZes=,tag:P7L5p5N9n7U+WJrwuYy1WQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbk94SkJUdzF5Unk5dXRw
            UUJ0eU1TTm1OWTJsVUJmTFFjR3N5Vm10dVQwClpKN0NQbTlwdEl3SUdjSHExYzY2
            V0E2QjNFb01MN2o4Q1pjYTRHTU9KS2MKLS0tIGRpek5hdDEzaUNySnZxcktPMXRF
            ZlpRVmhZTmNCMUZxekx3dFp5eCs2bDgKLOKAwcQxJI3esUFsXR1ws86gRGW0dg8P
            LATjwpCFhA7tN2MIDEqJGS7uxuq4zdUmjleB7NNtNOE0cOLkB8K4sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-16T16:54:17Z"
    mac: ENC[AES256_GCM,data:mgBxOAgdG2x96Syur02Wbhp2LUyVD355kqGO7H1PEqTqWvqdr2E0EuojhUFM0X8q+kJFXV2zf2pi45DopODzJ5s7Rw7KjSIF7KAhBqH6DrtPiaObtL86/ubt6m40/t7+l2zXWapWmXEwa7Nk/8NGuYw+70Nd/jUvQILt6xwzjMU=,iv:DpPcmaaM2303CCfYbLO5uEwaaus2eJDIfMrKpUk9850=,tag:tVcyCaR38bpPbLGk71UBbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
