apiVersion: v1
kind: Secret
metadata:
    name: emqx-secret
    namespace: flux-system
stringData:
    admin_password: ENC[AES256_GCM,data:69/D8CQsZeMuVa7u4/o=,iv:p79HNs8yRUfJ3LW23a+0xBEMqx2a7w020pga3QPeP4E=,tag:wli4QaPYyfey8WIdKRAwZA==,type:str]
    user_1_username: ENC[AES256_GCM,data:1YrFvKEmtRU+xg==,iv:/v6TfHoV50y5r4z/Kh3ekxaXE7YhAYqenmBlYZlWNps=,tag:/WsGRb/+NYWIfbYN6+kRRQ==,type:str]
    user_1_password: ENC[AES256_GCM,data:r/ue4zZDonrE/JWwA00=,iv:LqIsaMfyaurNBpNvxcyy6k/aelMyreqDUGU3gaPoDMM=,tag:AsusZklT6P9zTfhul8vaYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbk94SkJUdzF5Unk5dXRw
            UUJ0eU1TTm1OWTJsVUJmTFFjR3N5Vm10dVQwClpKN0NQbTlwdEl3SUdjSHExYzY2
            V0E2QjNFb01MN2o4Q1pjYTRHTU9KS2MKLS0tIGRpek5hdDEzaUNySnZxcktPMXRF
            ZlpRVmhZTmNCMUZxekx3dFp5eCs2bDgKLOKAwcQxJI3esUFsXR1ws86gRGW0dg8P
            LATjwpCFhA7tN2MIDEqJGS7uxuq4zdUmjleB7NNtNOE0cOLkB8K4sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-15T20:05:59Z"
    mac: ENC[AES256_GCM,data:qYKSDBevICU1DyH+CtpWia0KYMbGamVwHvMsU0L4gylFmlPuwAxVs+1C93g6Z7TCVnhJwZYSZS/lLTGCqMekEzPEgJhtqDUNED9A3wpASMxzmzR5eo1+tY3LJCB7cmDCZUkV55Jy2/cTgV4IZhFXPNITX0DNK7NDGKjMKCnSV3g=,iv:6fK3u9tpvZx7kvGJyEG3VacGkQvJEL/aaUOH5fGA8rE=,tag:Pahpg3BO2D55M+fcuMMwTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
