apiVersion: v1
kind: Secret
metadata:
    name: emqx-secret
    namespace: flux-system
stringData:
    admin_password: ENC[AES256_GCM,data:CN9F3rtK,iv:TF/J1goEo+iGTAkxz0hwTy0l3Q5Wp2l/nv7ptMtW1UI=,tag:OAN4UTNyigV8krO6fFW6pQ==,type:str]
    user_1_username: ENC[AES256_GCM,data:7PgKEA==,iv:C4tmZGinaDnm9fQqFstDdBrrJxmZGFdg3tCZJKIF1aI=,tag:DTJz89Fyb9brxg0GCr71Pg==,type:str]
    user_1_password: ENC[AES256_GCM,data:R7x4VA==,iv:7653Gvf70aFirzL9SMsmq85+X55lo02N0HzEo49TQ7s=,tag:IHdP/z39flCjbZ8keLVYvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbk94SkJUdzF5Unk5dXRw
            UUJ0eU1TTm1OWTJsVUJmTFFjR3N5Vm10dVQwClpKN0NQbTlwdEl3SUdjSHExYzY2
            V0E2QjNFb01MN2o4Q1pjYTRHTU9KS2MKLS0tIGRpek5hdDEzaUNySnZxcktPMXRF
            ZlpRVmhZTmNCMUZxekx3dFp5eCs2bDgKLOKAwcQxJI3esUFsXR1ws86gRGW0dg8P
            LATjwpCFhA7tN2MIDEqJGS7uxuq4zdUmjleB7NNtNOE0cOLkB8K4sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-15T21:00:36Z"
    mac: ENC[AES256_GCM,data:JeM4m6qD9NQQ8b9YtwkK1jVuniyXsqJ0xlRM9ebHpZi2mWv4ZeJbalbiSjxP5sfsRMy+sjNNjfss/npJ8On1BoF/GwTq2IfugT0DXQd1ObOCt6TG6VVp2d765RXFZ+4ws8TZcZXjes+4a5I2a5RHyTs9K7XAZt0jGNzZo5VL0+o=,iv:6qjDKdkrAbRkHmmih4ABsyGzh3xFUsOQOcM1mCmyBBg=,tag:SWeVhnazFfEp3CKN3SJVXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
