apiVersion: v1
kind: Secret
metadata:
    name: emqx
    namespace: default
stringData:
    admin_password: ENC[AES256_GCM,data:Qz7CR1RMxZExhZ+EwUw=,iv:3qwZapbmh7msvKlmLZNe4shmKNaTBo6bOooUuOYRPi0=,tag:W2iGnX8r856lxLT4sRKQWQ==,type:str]
    user_1_username: ENC[AES256_GCM,data:3oM8Oxx4UKhVaY2mRJU=,iv:FRstxMp9IKpOFdbx0DaiOJ7SXkxkXM3CHS2tcoX2NY8=,tag:WJ56GAB9d/1kUby+BjvbQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWa0JQSE9TczB1d0hybndN
            WXFaUkxDb2QvR05vNmE5aWMwMFJvdlZSWkhNClBQMmQwR2ZiYVVIOXNxbXppL3hs
            b0FvVDg3MVZ2cTBpVW53L1dUSWI5TFUKLS0tIDBSU3RYTlpPNU0xY3FQRG02ek8x
            M0xSOGJjd3FhUzhjK3ovNUJyTVFOQ0EKYZFuntXwHB5zWa6J6zEq7JK+YAObymJi
            ZoBFWJ3btPh9q81/EEGGjyXWwh6taBGzdR6xUJaYbIojbqRlL4Kikg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-12T02:27:54Z"
    mac: ENC[AES256_GCM,data:Tc6PesXQw04hu5jhqKfRCXLRPk/vaIoIEXj8hGILtl8xGbOKqqSnVukdwrQetNMp5Gg8iV9df3bf/uwm2JfnSGioSVuJ0C8O8JH4mcoB8W4FvoDO0lbxx9hkyz6fxvNfbM7sBrwvWEemomeRU/YvUAzaoW10tQqA5I/GNjOLBIE=,iv:H+BpjP/encqlRuA9NsbMYqKExbz40CNfOfHvmMwtB3A=,tag:TEepwxUx8BOyVIetRKga4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
