---
kubernetes:
  children:
    master:
      hosts:
        FleetCom-Node3:
          ansible_host: 10.0.30.13
          rook_devices:
            - /dev/disk/by-id/ata-SanDisk_SSD_PLUS_1000GB_224002803991
        FleetCom-Node7:
          ansible_host: 10.0.30.17
          rook_devices:
            - /dev/disk/by-id/nvme-SPCC_M.2_PCIe_SSD_AA221223NV01KG03817
        FleetCom-Node8:
          ansible_host: 10.0.30.18
          rook_devices:
            - /dev/disk/by-id/nvme-SPCC_M.2_PCIe_SSD_YT20230100813
    worker:
      hosts:
        FleetCom-Node1:
          ansible_host: 10.0.30.11
          # No secondary Drive Slot Available
        FleetCom-Node2:
          ansible_host: 10.0.30.12
          # No secondary Drive Slot Available
        FleetCom-Node4:
          ansible_host: 10.0.30.14
          rook_devices:
            - /dev/disk/by-id/nvme-Samsung_SSD_980_1TB_S64ANJ0RA66136P
        FleetCom-Node5:
          ansible_host: 10.0.30.15
          rook_devices:
            - /dev/disk/by-id/nvme-Samsung_SSD_980_1TB_S64ANJ0RA72021K
        FleetCom-Node6:
          ansible_host: 10.0.30.16
          rook_devices:
            - /dev/disk/by-id/nvme-Samsung_SSD_980_1TB_S64ANJ0RA71998K
        FleetCom-Node9:
          ansible_host: 10.0.30.19
          rook_devices:
            - /dev/disk/by-id/nvme-Samsung_SSD_980_1TB_S64ANS0W102840Y
