---
kubernetes:
  children:
    master:
      hosts:
        FleetCom-Node1:
          ansible_host: 10.5.0.3
        FleetCom-Node2:
          ansible_host: 10.5.0.4
        FleetCom-Node3:
          ansible_host: 10.5.0.5
    worker:
      hosts:
        FleetCom-Node4:
          ansible_host: 10.5.0.6
          rook_devices:
            - /dev/nvme0n1
        FleetCom-Node5:
          ansible_host: 10.5.0.7
          rook_devices:
            - /dev/nvme0n1
        FleetCom-Node6:
          ansible_host: 10.5.0.8
          rook_devices:
            - /dev/nvme0n1
