---
kubernetes:
  children:
    master:
      hosts:
        fleetcom-node1:
          ansible_host: 10.5.0.3
        fleetcom-node2:
          ansible_host: 10.5.0.4
        fleetcom-node3:
          ansible_host: 10.5.0.5
    worker:
      hosts:
        fleetcom-node4:
          ansible_host: 10.5.0.6
          rook_devices:
            #- /dev/nvme0n1
            - /dev/disk/by-id/nvme-Samsung_SSD_980_1TB_S64ANJ0RA66136P
        fleetcom-node5:
          ansible_host: 10.5.0.7
          rook_devices:
            #- /dev/nvme0n1
            - /dev/disk/by-id/nvme-Samsung_SSD_980_1TB_S64ANJ0RA72021K
        fleetcom-node6:
          ansible_host: 10.5.0.8
          rook_devices:
            #- /dev/nvme0n1
            - /dev/disk/by-id/nvme-Samsung_SSD_980_1TB_S64ANJ0RA71998K
