---
kubernetes:
  children:
    master:
      hosts:
        FleetCom-Node3:
          ansible_host: 10.5.0.5
          rook_devices:
            - /dev/disk/by-id/ata-SanDisk_SSD_PLUS_1000GB_224002803991
        FleetCom-Node7:
          ansible_host: 10.5.0.9
          rook_devices:
            - /dev/disk/by-id/nvme-SPCC_M.2_PCIe_SSD_AA221223NV01KG03817
        FleetCom-Node8:
          ansible_host: 10.5.0.10
          rook_devices:
            - /dev/disk/by-id/nvme-SPCC_M.2_PCIe_SSD_YT20230100813
    worker:
      hosts:
        FleetCom-Node1:
          ansible_host: 10.5.0.3
          # No secondary Drive Slot Available
        FleetCom-Node2:
          ansible_host: 10.5.0.4
          # No secondary Drive Slot Available
        FleetCom-Node4:
          ansible_host: 10.5.0.6
          rook_devices:
            - /dev/disk/by-id/nvme-Samsung_SSD_980_1TB_S64ANJ0RA66136P
        FleetCom-Node5:
          ansible_host: 10.5.0.7
          rook_devices:
            - /dev/disk/by-id/nvme-Samsung_SSD_980_1TB_S64ANJ0RA72021K
        FleetCom-Node6:
          ansible_host: 10.5.0.8
          rook_devices:
            - /dev/disk/by-id/nvme-Samsung_SSD_980_1TB_S64ANJ0RA71998K
        FleetCom-Node9:
          ansible_host: 10.5.0.11
          rook_devices:
            - /dev/disk/by-id/nvme-Samsung_SSD_980_1TB_S64ANS0W102840Y
