# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
    name: node-red-restic-secret
    namespace: default
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:cISGI8bJNM3o14J4HrXBBTqnUIZ9sdn/9QJcZdAaopQIClPVmthSe2+hQW25yOPbYMrOB56M5rMPEDCpVg==,iv:Z+0UwDSzcrPS/kk+PnXY67cuSOofnr26TCp7tSrTfgE=,tag:Mg0GuimCR97oshTtv/LkcA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:/G00+iTN4pudbNIjWNyvfm7lQvl+ELx4u6bZlwr989+h+5gdkTxRkQ==,iv:Rn2aCKMtlwc66IxgdgJVaEjYH9MJwn55Nfw+JXpEEKk=,tag:pv0dKlKkcNjryppZZ/eUMw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:wD7SYL+t+A==,iv:IimwZ2hB/Lltz3Svmpu7kBmum5B6OHbgmNyAx1ElADg=,tag:qcr6ROpn2bVJoC2A9Q6t/A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:KDEXSo8fbJeJvq7EyN/Abhpn0RQfRgVKwT3ao2bQ2sT5b8roSmnIFQ==,iv:HuPN3t/CzaWPqwePktMV+XB4zSxqyEEmvmJHL9wD+EE=,tag:1BMkPJXIQ7W9bU0Rkal7QA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbDdPalAyYXl4dkJDQVNU
            ZjZzK0hVS2hKa2N6MWpMNk1XQncreUF6dFJFCm11NDRDNWNsQm5DVkw3STE1OGxn
            dWUyL1Z3SUxDSnIzMlAyeHR0SFJrZTAKLS0tIGlVa3JMRko2cEp2dGF4WEh1OEVw
            RFNNRDdSSmZWRFVxN3pEUnJabGRjV1EKzQpuuCcU/mf5ZBu3C7GrIz1J22Heewtv
            SazOJjV7CfsgVJmPMuK0womBacKciLD9emUTNqgJY/EqFxDYEkQUcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-04T19:44:29Z"
    mac: ENC[AES256_GCM,data:EJ17djhxx4tdkQc6ZIcuaD6Mx6QfmMkLs4z2z2S7DGG9zIy8nt0/DI2igA/+6Gwi2yEhk3JSu4rHee+WBRsCzK5R/JIuXMxiXDtdVBiSRWjXFZI/V96O8htpkI7bqK1aqjihciNcHCwwAtZrbicDU8D4FStL9lzGL1ohSe61ims=,iv:fcGcyx6IgPfJUYaFIbjqBkPLTNNA8wHHeuKnOFJNcqk=,tag:tk5eXqjRltQkORXRnP1zZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
