apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:NBMLSyfm,iv:RN5qm0SvIUcmFVivgdKN62X4RoHgO8ld/hSS8jptINw=,tag:zsk3LlDS1YuHWi0VCQuLvg==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:nMR89zdjT97A63oUvmUI,iv:MhqSfg5Hywz0vUP0BK0JKRvuoBJpCUTI0TYiQ3hgRxI=,tag:7mmge6AubDb9K0WhB4CofQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbk94SkJUdzF5Unk5dXRw
            UUJ0eU1TTm1OWTJsVUJmTFFjR3N5Vm10dVQwClpKN0NQbTlwdEl3SUdjSHExYzY2
            V0E2QjNFb01MN2o4Q1pjYTRHTU9KS2MKLS0tIGRpek5hdDEzaUNySnZxcktPMXRF
            ZlpRVmhZTmNCMUZxekx3dFp5eCs2bDgKLOKAwcQxJI3esUFsXR1ws86gRGW0dg8P
            LATjwpCFhA7tN2MIDEqJGS7uxuq4zdUmjleB7NNtNOE0cOLkB8K4sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-04T01:12:06Z"
    mac: ENC[AES256_GCM,data:ec00+YX03p5akK1vFPyLigTOVHW8uVQdn4LJzbFhxwmIe3FasKn8eOxE6y49zMMMprr5EybQJ+C3CvR9WfDHkjR9BAIXrwO+49g55lvKT96z1igXlgXQXdkEbCRtKOuZ+VfoFRp1D8ALAnOd168nlZwItQlHQ5Huwqu3CMxy7H0=,iv:qjroNOm6A/ggP+yZVOEfSrACdshAfBYw72COLJbM6LI=,tag:6oEP4ISlt9u2kxD+tgaHOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
