apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: default
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:NBMLSyfm,iv:RN5qm0SvIUcmFVivgdKN62X4RoHgO8ld/hSS8jptINw=,tag:zsk3LlDS1YuHWi0VCQuLvg==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:nMR89zdjT97A63oUvmUI,iv:MhqSfg5Hywz0vUP0BK0JKRvuoBJpCUTI0TYiQ3hgRxI=,tag:7mmge6AubDb9K0WhB4CofQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbk94SkJUdzF5Unk5dXRw
            UUJ0eU1TTm1OWTJsVUJmTFFjR3N5Vm10dVQwClpKN0NQbTlwdEl3SUdjSHExYzY2
            V0E2QjNFb01MN2o4Q1pjYTRHTU9KS2MKLS0tIGRpek5hdDEzaUNySnZxcktPMXRF
            ZlpRVmhZTmNCMUZxekx3dFp5eCs2bDgKLOKAwcQxJI3esUFsXR1ws86gRGW0dg8P
            LATjwpCFhA7tN2MIDEqJGS7uxuq4zdUmjleB7NNtNOE0cOLkB8K4sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-04T01:21:45Z"
    mac: ENC[AES256_GCM,data:Ih5IpbH/gZ8lQA3GSRAbDh2osiiXgSzKCXJRww8ic+7d9eeTb1DM9r+/DcIQ3Uk0EkGaTFi1fldp5jnnB+7EIGEyouyBYXMWHH71U59cQyC36wCMzD7nFTj+0xFvDmexiu2dA1xmzOfLOpfRd8z6SGPBf9LEfBJguxlVtp4hnHw=,iv:mn4MamNOMEOtbu6Yfuz9CdmqAlh3pmQ63J/TyAfbXxE=,tag:0icCvNA27QpYL2kJRXCfSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
