---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wireguard
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      type: statefulset
    image:
      repository: docker.io/linuxserver/wireguard
      tag: 1.0.20210914
    env:
      TZ: "${TIMEZONE}"
      SERVERURL: &host "wg.${SECRET_DOMAIN}"
      SERVERPORT: 51820
      PEERS: 1
      PEERDNS: "auto"
      INTERNAL_SUBNET: "10.13.13.0"
      ALLOWEDIPS: "0.0.0.0/0"
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_MODULE"]
      sysctls:
        net.ipv4.conf.all.src_valid_mark: 1
    service:
      main:
        ports:
          http:
            port: 51820
            targetPort: 51820
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns.home.arpa/enabled: "true"
          hajimari.io/icon: mdi:vpn
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: wireguard-tls
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 100Mi
        storageClass: ceph-block
        labels:
          snapshot.home.arpa/enabled: "true"
      - name: modules
        mountPath: /lib/modules
        accessMode: ReadWriteOnce
        size: 100Mi
        storageClass: ceph-block
        labels:
          snapshot.home.arpa/enabled: "true"
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 500Mi
