apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:/l2iM9LVZCs4A4UbIXoGEIXOkJnf0030Lhqg5341TKEmqnWeK9BXHIfQ1kkRRWr7mSoQ410vu2xS4T/MqDciL2fq5QCC8zoc8N9hyyzSdfYbR/jt61Mdo077pCY86qgcO02w2Wh4v8bk7hmZIso7uJDh/1JhuCtOj7ijmxcfP6wN7KFDGjgn6NRIRnifzlVO4b38lBVZGBotf5jioTnPlSEEQSEAskdfzz0rLedd/dnCyR1Te5m9jr81zAAbYkgH4wuzAsNC0OMdzvgLexoW78trbwc3f28mhy5xV1VFtxddaAmqGm+T93hdA87SZjXxQoF5TCnvgieoE4LMGi+z65vhseNf05XnqrzskbjDLZxoxl/VgvdWMKO53T4Vfk7o2ppXNHMi2GJ1UPmtWlX5MNyRQloHvCKnG92kiJFEIvbYm9Vq5deIXSOTBITJIHTMOyyKZ8u7fGRUbkVhb5WdH2GMlokY/GPpfD08foDd4t0EMxk8o+VdfRFj3+L+8XOpwvAqxpjw8nfQwUjjzkFKV6hvqtl+8Z5mjXrtSEeZBj7Z4pxAtHqYWzTrCqtT2jF4AAALMoDE6xF1iDZsrcc/MtwGjeU7JR3kmTD+q+FjeEmZCAAW/asAKfzBhrvpsVvorq5nEQ==,iv:NipPf2CiFURPgeLiS2ok5rJrmZ7gGUnG2JO1R5x2fIY=,tag:XQuDelxBhTPHGU12zb8eZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZmN6RklEcUxIZHVuTWRM
            VFdOQlBtWUZVaTFicGFPRkQwYmhOWFZlaUVvCk04N1lMYUJiUDRYRXVIYTFUT0tp
            SURMLy9IbUU2Ti9mRkZWdSsvVHVWMWcKLS0tIDUyZkZrTmw2cEJMVUZqR0xNWXA3
            ZEtHMnN2cHpNbG92U3ZHWFdVRTBvUkEKKQH/bi6NgmaivQOxe17ukNkaDwVsF2j0
            VWeABGphKMRdkiH48XRN3iVoEUvKQ7yIRKkcyINiVJyxcKfzwfyrIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-02T03:41:21Z"
    mac: ENC[AES256_GCM,data:tQVFpyVWFGjznnH4GKy+7RQdGjckEGaAL6EyB6X78pEvoi5KOT2bZNifqYxaa6Ovlw71/YxmOuhAI/B8Ld8GHBqauHsq9Pts9h5dwIpOE/Ed+jXBvjJuRsMR86U1GrUIj1y4j8IbXEzF9TTESYBkfGQTGR2z1s6GaJilbPYbCzM=,iv:+ewy2gxhbZ3+tqHAzW+F7rFtNLmKzZ4qJKizFPwt4hA=,tag:9RixRmkvA4v2iOWFZO5KHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
