---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./audiobookshelf/ks.yaml
  - ./bazarr/ks.yaml
  - ./echo-server/ks.yaml
  - ./emqx/ks.yaml
  - ./hajimari/ks.yaml
  - ./lidarr/ks.yaml
  - ./minio/ks.yaml
  - ./nodered/ks.yaml
  - ./overseerr/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./tautulli/ks.yaml
  - ./theme-park/ks.yaml
  - ./uptimekuma/ks.yaml
