---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./audiobookshelf/ks.yaml
  - ./bazarr/ks.yaml
  - ./echo-server/ks.yaml
  - ./hajimari/ks.yaml
  - ./lidarr/ks.yaml
  - ./overseerr/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
