---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-teleport
  namespace: Default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
