apiVersion: v1
kind: Secret
metadata:
    name: teleport-cluster-secrets
    namespace: Default
stringData:
    secret: ENC[AES256_GCM,data:7b65urTEvgssCWHkAN8J4cD+8qT6COyJig==,iv:0HuhbYq/1/sQ3CbgsgwEDlCDc8xFafN1i3RE9tHniso=,tag:Bk5rl2AbRJ0VdWgzSLYYAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbk94SkJUdzF5Unk5dXRw
            UUJ0eU1TTm1OWTJsVUJmTFFjR3N5Vm10dVQwClpKN0NQbTlwdEl3SUdjSHExYzY2
            V0E2QjNFb01MN2o4Q1pjYTRHTU9KS2MKLS0tIGRpek5hdDEzaUNySnZxcktPMXRF
            ZlpRVmhZTmNCMUZxekx3dFp5eCs2bDgKLOKAwcQxJI3esUFsXR1ws86gRGW0dg8P
            LATjwpCFhA7tN2MIDEqJGS7uxuq4zdUmjleB7NNtNOE0cOLkB8K4sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T03:51:09Z"
    mac: ENC[AES256_GCM,data:DEyu14b0CUOMnSQ6wAvLaqbfwGVs/LvO075Kpu8nvv9efASB3zkqTfr5KamGP573z0jsm9AthW130+03vpWWQzFefNjwoZ08tr3vxORpAsgbYwEGHCIqbU7rk9EhpiLNZunySFzEUyqJHucV0Lxey582aXRSzVo4Fx1wmN9AmPA=,iv:VyKJfT39fJQ5leqP3ykFfbM08p5U4dFoOl9WSSlrepg=,tag:E9b1gJSZpjd7n6nK0Nxt6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
