apiVersion: v1
kind: Secret
metadata:
    name: teleport-cluster-secrets
    namespace: default
stringData:
    secret: ENC[AES256_GCM,data:7b65urTEvgssCWHkAN8J4cD+8qT6COyJig==,iv:0HuhbYq/1/sQ3CbgsgwEDlCDc8xFafN1i3RE9tHniso=,tag:Bk5rl2AbRJ0VdWgzSLYYAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbk94SkJUdzF5Unk5dXRw
            UUJ0eU1TTm1OWTJsVUJmTFFjR3N5Vm10dVQwClpKN0NQbTlwdEl3SUdjSHExYzY2
            V0E2QjNFb01MN2o4Q1pjYTRHTU9KS2MKLS0tIGRpek5hdDEzaUNySnZxcktPMXRF
            ZlpRVmhZTmNCMUZxekx3dFp5eCs2bDgKLOKAwcQxJI3esUFsXR1ws86gRGW0dg8P
            LATjwpCFhA7tN2MIDEqJGS7uxuq4zdUmjleB7NNtNOE0cOLkB8K4sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T04:23:17Z"
    mac: ENC[AES256_GCM,data:9waZpS1EK5Cc411wXafs2yPM7xdwrVg+iG8n/Tx+RVZwUF2gwKFr66SNF2+l8q1jPOWFqgCBNd2HTPGgC1QgRL1c5/P8KhDWHHFUqBUeLhJTDGDDUOboFMCukbGbyvDdXixREDb9ZXmt5Eavlj0jxeMYX1XxZdX+hfDRDJqCPdI=,iv:S+Y40MoQQbwiQdjy5GqcHrjnIPwqXTDugIwA05lP8mo=,tag:Exk1uSEsubKoXEftuVs7Tw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
