apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:2t9o1LVxdlpemGZykINlvUZhPma3tBGissyZwoWTXPtUa/Dx45sd4AhJxkLQKdzCPLrfEsm8HMkKRISq,iv:YaDqojgkTtieAsEsYkO3KCNyMvxy9gS1nmab0Zo8zBY=,tag:77r0uHIObYG4lpqwmLa+1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSngyV3NIVE05WXJyY3Q0
            Vzhhb05LM002TGRFaXFUMmt5R1RqY2oyVW5FCjR3aHdJanZ4SHVwVU53ZGRIN240
            QTVlNFpYbmhkWkcyamJhbHhuNENBbncKLS0tIFJSdEk0WUpmUU5keENsUzdkd2Nx
            RHlHd2V6aWt0dEE0RGNFbXVLTU16QmsKEVCEjzRa4yVNIGie9WMSrGYJCvh2Ca+E
            cfTW6/oU0qtOAUWCuOcTE14uefrw5vZwrsnUzLaaudHXgIoZTF1fVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-08T05:09:32Z"
    mac: ENC[AES256_GCM,data:siHf+IpK4bgxa2D1JKQzSgzTuS9vrcQQZay4ydfT/mlktp4XQRQy1RnrRlbeQryXAguGO2XOas/k2VFREkFal6SuhfsU3IZtM9zW/vCE+dGt9xKY4y+spIc/XPTeP+99MEgZ4upUZ/InIgQLHGX3esUmEtflELZK/vMRLgIvFPk=,iv:0n1Z/htSiNFMBCICJ3QHrv1FVFAoyrHEVfJaRhHkz8M=,tag:/O42wVHRhf+FBuZ78LkqtQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
