apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:GmEVV48FEidaWB05cwQ0J2BloygEWqu7kcoh05LUpAH6cGr95JV0nTpXU8VGdv98Y1TL0Q2b+EJL9gNg,iv:TjAmDkH2JOjs52DaUyJfIOdhHLByZ6NH5fbJ8UfzjEo=,tag:BRxlYoGWo+NgTFiehqx2tA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSngyV3NIVE05WXJyY3Q0
            Vzhhb05LM002TGRFaXFUMmt5R1RqY2oyVW5FCjR3aHdJanZ4SHVwVU53ZGRIN240
            QTVlNFpYbmhkWkcyamJhbHhuNENBbncKLS0tIFJSdEk0WUpmUU5keENsUzdkd2Nx
            RHlHd2V6aWt0dEE0RGNFbXVLTU16QmsKEVCEjzRa4yVNIGie9WMSrGYJCvh2Ca+E
            cfTW6/oU0qtOAUWCuOcTE14uefrw5vZwrsnUzLaaudHXgIoZTF1fVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-29T16:40:28Z"
    mac: ENC[AES256_GCM,data:BYXG0/Vlb05Grjudm2b8hpiSRTNQyPrtHy2tzoMTzfwvL4eT9IGGgki1zzqBVLMpc0v7ICCaktLtOGk/TTE0zFaPBIFqdm+92bofPTJl14KXRzoNhzkeBwTwP0ETiVL0hYlKXS521FnWGnCLCjtxqv+9OlqlT2O+gjbmZ9hqRFk=,iv:yrZG5Gbu3CHLRcWBw50daGgUXUM/EeO3ZLDqXZvLDBg=,tag:TX2kuqy2gRXOA+TrX8K9oQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
