apiVersion: v1
kind: Secret
metadata:
    name: vpnconfig
    namespace: vpn
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:YW8avEh/rw==,iv:qnfK5J4bvVDYdLgjwlVe5yyIRzc7K1Hv7JX7cDK/Ma8=,tag:oXHcMLJJyOzyddOPTFz7bA==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:jgSc4Fb23XXlsdvF9hQ6BNdUuJ9Tw8fw8u9YulCTWdxQSm7h7lZqQzDDbDA=,iv:kRoqUFV+ZtPnUh8vpLY2Ppu96t+GB6EM6e71rRiF68Y=,tag:95o9vi7bYId5pKURsj8RVA==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:sePmnUWeUfdvoSn6ocI6HA==,iv:gG+k/kYbatZ3G21comdIp5LWYUm9NiAhA98Qb4Kikak=,tag:EwicuUfTmQODggsSTW95iA==,type:str]
    #ENC[AES256_GCM,data:rMvJoBvmb2Y9rESgwzpTcH4QcrDeMqM9sg==,iv:Rn2cYKxdUhmm7R0n3lD82flUKbfElNnuKMBB+XemZIc=,tag:6eRN/G95WPdIPP2Ig4EP+A==,type:comment]
    #ENC[AES256_GCM,data:fyEE38lwg3e23ustDtf3mF4dd15c,iv:ULSXOrlAD/QXQxaBthohVCnZ2wy+A/8Sm3skspUEK1o=,tag:NSDr33EsYQjCdFvmUHi6dw==,type:comment]
    #ENC[AES256_GCM,data:nWyIUt0upWBf5jyYOtOUVoqQf76XcqWqveCdntsLiNbg,iv:R8DHxib06VuXQ1dc0zDJkdnrWacudcGWpvlCMmickag=,tag:Jm7ZzM9G181KZj52KZUUiQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbDdPalAyYXl4dkJDQVNU
            ZjZzK0hVS2hKa2N6MWpMNk1XQncreUF6dFJFCm11NDRDNWNsQm5DVkw3STE1OGxn
            dWUyL1Z3SUxDSnIzMlAyeHR0SFJrZTAKLS0tIGlVa3JMRko2cEp2dGF4WEh1OEVw
            RFNNRDdSSmZWRFVxN3pEUnJabGRjV1EKzQpuuCcU/mf5ZBu3C7GrIz1J22Heewtv
            SazOJjV7CfsgVJmPMuK0womBacKciLD9emUTNqgJY/EqFxDYEkQUcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-05T20:09:04Z"
    mac: ENC[AES256_GCM,data:fN16CHvaKZ2o2ubDdzic6swjfKLQa3yu9oBelVxjfVuaVMXsMkkirN2tcgmv35cLb0z63pBrn5An/yfs/KMn1/J7AVbmVjMJhpqDMAVCsVEPeofgQa/IxemkQfKeOl/BSO7MebNNZeXlEI4DBqcYuC+R037rm+IiHVCLH2Y+N0E=,iv:f8vVVR0wCA6W2uqSHZpCU4BBtSliUE3DWyU1zCTc2BY=,tag:3mcDV/xQKcVB5TAJgSElpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
