apiVersion: v1
kind: Secret
metadata:
    name: downloads-gateway-vpnconfig
    namespace: vpn
stringData:
    #ENC[AES256_GCM,data:VCC7pnvTtqamNZ8+t2GiUUjjNlFgkzAB3n7v0Vk=,iv:q+rJq4Qum7rG5lntSrl6Cq1ceaAgrTqiU/ns14dYHrc=,tag:FwLDppzR67Lmdq5VexFC9w==,type:comment]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:jgSc4Fb23XXlsdvF9hQ6BNdUuJ9Tw8fw8u9YulCTWdxQSm7h7lZqQzDDbDA=,iv:kRoqUFV+ZtPnUh8vpLY2Ppu96t+GB6EM6e71rRiF68Y=,tag:95o9vi7bYId5pKURsj8RVA==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:sePmnUWeUfdvoSn6ocI6HA==,iv:gG+k/kYbatZ3G21comdIp5LWYUm9NiAhA98Qb4Kikak=,tag:EwicuUfTmQODggsSTW95iA==,type:str]
    SERVER_CITIES: ENC[AES256_GCM,data:LMFJlh6Lwj18jw==,iv:Uf2VemNZqUVrgdW4fgQwXjZy2z9iMQO18aUoUWgMRiE=,tag:515fAX1IoUWdBzzQy4isMg==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:U59m,iv:6rO4jnhbMOuNXkMgGKGeWDJJOM6DnK8fLT/hso9bRu4=,tag:HLGxnJjNFkeSvbaRzBdHQQ==,type:str]
    SERVER_HOSTNAMES: ENC[AES256_GCM,data:P1bo4w4R5w/cM6meeLu9,iv:+31Pe/0V2ikQ1X2WltINp8uZrK6/OUWx5r9eEjXkL9M=,tag:5SzeIAQiqrp+UlgppuddFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbDdPalAyYXl4dkJDQVNU
            ZjZzK0hVS2hKa2N6MWpMNk1XQncreUF6dFJFCm11NDRDNWNsQm5DVkw3STE1OGxn
            dWUyL1Z3SUxDSnIzMlAyeHR0SFJrZTAKLS0tIGlVa3JMRko2cEp2dGF4WEh1OEVw
            RFNNRDdSSmZWRFVxN3pEUnJabGRjV1EKzQpuuCcU/mf5ZBu3C7GrIz1J22Heewtv
            SazOJjV7CfsgVJmPMuK0womBacKciLD9emUTNqgJY/EqFxDYEkQUcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-06T02:26:44Z"
    mac: ENC[AES256_GCM,data:Kj6mdwOeUMr+gjXzpF/S/Y280/tiYC4gnTW1YhI09xUMxE2J8KGZin12XKlCET2Ah3xxZENGY3E2ngHOi3j5hBLEdEkYh9YVjZ1MOG9uXDvN33eKKRm1NSHvKcXKnleadGYNqT4R+374w7sIaPUkHcmKiY+YVDC+fA6TDMe813s=,iv:2CXr1LFIE3uDpKmvdtkBP70f1dVyvXxEH9ooeE0RZio=,tag:MTB194+RmKY5RzmgHI10QA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
