apiVersion: v1
kind: Secret
metadata:
    name: vpnconfig
    namespace: vpn
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:YW8avEh/rw==,iv:qnfK5J4bvVDYdLgjwlVe5yyIRzc7K1Hv7JX7cDK/Ma8=,tag:oXHcMLJJyOzyddOPTFz7bA==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:jgSc4Fb23XXlsdvF9hQ6BNdUuJ9Tw8fw8u9YulCTWdxQSm7h7lZqQzDDbDA=,iv:kRoqUFV+ZtPnUh8vpLY2Ppu96t+GB6EM6e71rRiF68Y=,tag:95o9vi7bYId5pKURsj8RVA==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:sePmnUWeUfdvoSn6ocI6HA==,iv:gG+k/kYbatZ3G21comdIp5LWYUm9NiAhA98Qb4Kikak=,tag:EwicuUfTmQODggsSTW95iA==,type:str]
    SERVER_CITIES: ENC[AES256_GCM,data:ba4KFDhjM/rNFQ==,iv:Xh8Abbt9N6POwm6nfClH+2cCin59CliLXP7hGyzRBBY=,tag:fjdLLolddL1r+tOXtk152g==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:O86u,iv:shGhiabsOYKI1TK5q9/jK/CqKy1AHQTJhhY70UF6SSg=,tag:wTUGSt8Wy3alhHwVXSzG9w==,type:str]
    SERVER_HOSTNAMES: ENC[AES256_GCM,data:PRoV7PfBH7apGx+n7U+f,iv:L15JptRPN5M2MAkw+Iw+fOOD+Lavwmcl5pTTegy+IiA=,tag:22HDRGqCMepvImL0jHB+SQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbDdPalAyYXl4dkJDQVNU
            ZjZzK0hVS2hKa2N6MWpMNk1XQncreUF6dFJFCm11NDRDNWNsQm5DVkw3STE1OGxn
            dWUyL1Z3SUxDSnIzMlAyeHR0SFJrZTAKLS0tIGlVa3JMRko2cEp2dGF4WEh1OEVw
            RFNNRDdSSmZWRFVxN3pEUnJabGRjV1EKzQpuuCcU/mf5ZBu3C7GrIz1J22Heewtv
            SazOJjV7CfsgVJmPMuK0womBacKciLD9emUTNqgJY/EqFxDYEkQUcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-05T04:41:50Z"
    mac: ENC[AES256_GCM,data:UPJ4Q6hz8b1MtOoaGKbBghKi5g6mG/SotY/aOPKL48/Lt2DAhEn07UpIIgVAC5ZiohRzA2awwIj6Q3Yx0Myo+M3tso7FjZvoSPF30M/M0KFoNsHyKSGHvnDmhdayOGadG5POJM0ccG00pWO1J8WCw4hejeNoEgPgHc8tYS1Ahm0=,iv:cjekAMJHgAoLyT52rJjJf1uUzZ2oXdM0kBZRXAhdniM=,tag:xNR/IjFy8NEX6wKEVnymEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
