apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:4FGB4++PcX0NuAYSPA==,iv:wwAv048+Zy40zg6vffkqzs0D3bpKURc6HwSHL+ckMss=,tag:a5VCQotg5h9Bm9mlSqOIjw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:UlzgzwWAVmPZmBMWt46goD9l1PIfHz4QF+Q=,iv:VPzIR00EdbjOvKjvxglQGiEYQBxjMc87qfnFqLdrl2Y=,tag:XcozgK3AyOxA5TCdzj8xbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbk94SkJUdzF5Unk5dXRw
            UUJ0eU1TTm1OWTJsVUJmTFFjR3N5Vm10dVQwClpKN0NQbTlwdEl3SUdjSHExYzY2
            V0E2QjNFb01MN2o4Q1pjYTRHTU9KS2MKLS0tIGRpek5hdDEzaUNySnZxcktPMXRF
            ZlpRVmhZTmNCMUZxekx3dFp5eCs2bDgKLOKAwcQxJI3esUFsXR1ws86gRGW0dg8P
            LATjwpCFhA7tN2MIDEqJGS7uxuq4zdUmjleB7NNtNOE0cOLkB8K4sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-29T16:40:27Z"
    mac: ENC[AES256_GCM,data:v+uEbHTO07VgaE5kQeuV/OgjysLI0WFh2I1Y8IBi1DhJL7wYeX7P9XXrmb0wt8brDWfrhcF84wvc+6A4yDB9axr6tf018sG3FoEsfQLpVvzKH1jSWoY+EI+nbtVDuUTX55h2dpurOvxjkv0KmKCdFROgjjW2JqWdNmBqhNMDOP4=,iv:snaADAFxbcUI2Hh7bYxja2738r2gMRb0dg3xf/XB7EY=,tag:XKmdfNJonaqsHtObjbVEow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
