apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:4FGB4++PcX0NuAYSPA==,iv:wwAv048+Zy40zg6vffkqzs0D3bpKURc6HwSHL+ckMss=,tag:a5VCQotg5h9Bm9mlSqOIjw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:UlzgzwWAVmPZmBMWt46goD9l1PIfHz4QF+Q=,iv:VPzIR00EdbjOvKjvxglQGiEYQBxjMc87qfnFqLdrl2Y=,tag:XcozgK3AyOxA5TCdzj8xbw==,type:str]
    SONARR__API_KEY: ENC[AES256_GCM,data:VehufPytTFtJiHzPHWXEsYNzlC+sFAfcFv2k5cESbpY=,iv:E089r6G7vNb2CVs75TaTYjYQF1eEdEbNd49AQcbJUPg=,tag:ZFZOPScnc5oAxsX+kGt9kw==,type:str]
    RADARR__API_KEY: ENC[AES256_GCM,data:RZi4tUAbUJJqrygDYejH6EBic5C56TraaQ41n0d5ZHM=,iv:uW9Qht2I/MXXiKDSmWvOjLXHbTMmXyBD990KhIMciMg=,tag:AoaqxCFoaEfI0PCm72GnGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbk94SkJUdzF5Unk5dXRw
            UUJ0eU1TTm1OWTJsVUJmTFFjR3N5Vm10dVQwClpKN0NQbTlwdEl3SUdjSHExYzY2
            V0E2QjNFb01MN2o4Q1pjYTRHTU9KS2MKLS0tIGRpek5hdDEzaUNySnZxcktPMXRF
            ZlpRVmhZTmNCMUZxekx3dFp5eCs2bDgKLOKAwcQxJI3esUFsXR1ws86gRGW0dg8P
            LATjwpCFhA7tN2MIDEqJGS7uxuq4zdUmjleB7NNtNOE0cOLkB8K4sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T02:04:51Z"
    mac: ENC[AES256_GCM,data:OdT4FXfj1NKAvsaJ1ood2bPP2Uyrjt2VEov/1ocC6tLPOwBH/y3VzP5YeyMt5L3kMCSnAalODZEmx0BWTAdgdzrMnaFAufgEdOTBL4ANNSzT1zPfSx5mf1WhZk3tPmvc3VXaOAGEm3+peDErHcnGlyBIi3eqKIPbzuFCfveY1zc=,iv:63fGhWoIxrhSng5BJFpkkS5RyGdGszY9Z/XD6v9ea90=,tag:N1CZNjB3YFSPFpzgU1EzAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
