---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: teleport-cluster
resources:
  - certificate.yaml
  - helmrelease.yaml
  - config-pvc.yaml
  - secret.sops.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/name: teleport
  app.kubernetes.io/instance: teleport
