---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app teleport
  namespace: teleport-cluster
spec:
  interval: 30m
  chart:
    spec:
      chart: teleport-cluster
      version: 11.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: teleport
        namespace: flux-system

  values:
    clusterName: teleport.${SECRET_DOMAIN}
    #kubeClusterName: cluster-0

    authentication:
      type: github

    tls:
      existingSecretName: teleport-tls

    # annotations:
    #   service:
    #     coredns.io/hostname: teleport.${SECRET_DOMAIN}

    persistence:
      enabled: true
      existingClaimName: teleport-cluster-config-pvc

    service:
      spec:
        loadBalancerIP: ${METALLB_TELEPORT_ADDR}
