apiVersion: v1
kind: Secret
metadata:
    name: downloads-gateway-vpnconfig
    namespace: vpn
stringData:
    #ENC[AES256_GCM,data:8d+zvsTH+QPDgaCbi6jfwfvNKuQMFZAuORJpm/pS,iv:W+aZ6mtM4eHEf8VLHssN4dP6gEPKYO+IQgIn+o/FdS8=,tag:Ax6APH7AmpPpagWSu2UcaA==,type:comment]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:3dD6m7+FANpDyDYxVjyg+RF6tQLIrXzmL3p5M9kObVcMwJmtMEQBzh0zEC8=,iv:sw3hqGFXyQCRIs8vf3d7yBkwyLtsIlDkYZ1vqvG18kI=,tag:Me3+YjLzsN766A9NRUgerg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:9xPQvfRWX35TVsRbu8IF,iv:/wpb49JONKyaz9PWehU2IoN8jPUfSwhncGzQcr1Zjh8=,tag:d8MWTWxnx1t+U/sa0+iBWw==,type:str]
    SERVER_CITIES: ENC[AES256_GCM,data:LMFJlh6Lwj18jw==,iv:Uf2VemNZqUVrgdW4fgQwXjZy2z9iMQO18aUoUWgMRiE=,tag:515fAX1IoUWdBzzQy4isMg==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:U59m,iv:6rO4jnhbMOuNXkMgGKGeWDJJOM6DnK8fLT/hso9bRu4=,tag:HLGxnJjNFkeSvbaRzBdHQQ==,type:str]
    #ENC[AES256_GCM,data:QtPgggR/TGuRLAhVcvzj1sWKcnVcbj2zr0XDhprnZ9DuPg==,iv:YDnryvrq60Ii3MIwgcB+vpsNtU581BnyHNtnWS4t1H0=,tag:27uMvvALQU+xZHCeFIGE3A==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbDdPalAyYXl4dkJDQVNU
            ZjZzK0hVS2hKa2N6MWpMNk1XQncreUF6dFJFCm11NDRDNWNsQm5DVkw3STE1OGxn
            dWUyL1Z3SUxDSnIzMlAyeHR0SFJrZTAKLS0tIGlVa3JMRko2cEp2dGF4WEh1OEVw
            RFNNRDdSSmZWRFVxN3pEUnJabGRjV1EKzQpuuCcU/mf5ZBu3C7GrIz1J22Heewtv
            SazOJjV7CfsgVJmPMuK0womBacKciLD9emUTNqgJY/EqFxDYEkQUcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-16T01:11:33Z"
    mac: ENC[AES256_GCM,data:V7Xz3enTwd6UauOA+qOM6YvxiMTJhljTej/FZ/0r969USuMNjqS8d3jteJ1QsyMAMwParaHqV0qC0+JRArw0clYGbAtrFVR1SZ5zagbWrn5J5r86s7hu9c6YORZ8k0U0tfTUy6Qaeae4nIXgquCCvd1aJE4w9+pC/frY9sxuUIo=,iv:/xYZqlz2q4j8hDyGVv1vhVA+VKZUL3dZEL4xter22P4=,tag:DMviS0nnvbil5OH3Y6lU7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
